networks:
  webappnet:
    external: true

services:
  wlib-backend:
    image: ctadel/wlib-backend:latest
    container_name: webapp-wlib-backend
    restart: unless-stopped
    environment:
      - CORS_ALLOWED_ORIGINS=http://192.168.10.10:10001,http://library.webapps.griham.com,https://webapp-library.prajwaldev.com.np
      - TZ=${TZ:-'UTC'}
    ports:
      - "10002:8000"
    networks:
      - webappnet
    volumes:
      # You must manually create the sqlite.db file in the CONFIG_DIR
      # and ensure it has all necessary tables and schema.
      - ${CONFIG_DIR}/webapps/wlib-backend/sqlite.db:/app/sqlite.db
    labels:
      glance.name: FastAPI - Backend
      glance.parent: webapp-wlib-frontend
      glance.hide: false

  wlib-frontend:
    image: ctadel/wlib-frontend:latest
    container_name: webapp-wlib-frontend
    restart: unless-stopped
    environment:
      - TZ=${TZ:-'UTC'}
    ports:
      - "10001:80"
    depends_on:
      - wlib-backend
    networks:
      - webappnet
    labels:
      glance.id: webapp-wlib-frontend
