global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Docker Containers'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'System Metrics'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'Watchtower'
    scrape_interval: 1d
    metrics_path: /v1/metrics
    bearer_token_file: /etc/prometheus/bearer_token
    static_configs:
      - targets: ['watchtower:8080']
