networks:
  medianet:
    external: true

services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    networks:
      - medianet
    restart: unless-stopped
