networks:
  medianet:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/series:/series
      - ${MEDIA_DIR}/music:/music
    ports:
      - "8096:8096"
    networks:
      - medianet
    restart: unless-stopped
