networks:
  homenet:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONFIG_DIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - homenet
    ports:
      - "8123:8123"
