pages:
  - name: Dashboard
    width: slim
    hide-desktop-navigation: false
    center-vertically: true
    columns:

      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: Services
                hide-mountpoints-by-default: true
                mountpoints:
                  "/":
                    name: System
                    hide: false
                  "/data/config":
                    name: SanDisk microSD
                    hide: false
                  "/data/media":
                    name: SSD Media Drive
                    hide: false

          - type: dns-stats
            service: adguard
            url: ${ADGUARD_CHECK_URL}
            username: ${ADGUARD_USERNAME}
            password: ${ADGUARD_PASSWORD}

          - type: monitor
            cache: 1m
            title: Service Monitoring
            sites:
              - title: Grafana
                url: ${GRAFANA_DEFAULT_DASHBOARD}
                check-url: ${GRAFANA_CHECK_URL}
                icon: di:grafana
              - title: Prometheus
                url: ${PROMETHEUS_URL}
                check-url: ${PROMETHEUS_CHECK_URL}
                icon: di:prometheus
              - title: cAdvisor
                url: ${CADVISOR_URL}
                check-url: ${CADVISOR_CHECK_URL}
                icon: sh:cadvisor
              - title: Node Exporter
                url: ${NODE_EXPORTER_URL}
                check-url: ${NODE_EXPORTER_CHECK_URL}
                icon: sh:antora-dark

          - type: monitor
            cache: 1m
            title: Web Apps
            style: compact
            sites:
              - title: Portfolio
                url: ${PORTFOLIO_URL}
                check-url: ${PORTFOLIO_CHECK_URL}
              - title: Web Library - Frontend
                url: ${WEBLIB_FRONTEND_URL}
                check-url: ${WEBLIB_FRONTEND_CHECK_URL}
              - title: Web Library - Backend
                url: ${WEBLIB_BACKEND_URL}
                check-url: ${WEBLIB_BACKEND_CHECK_URL}
              - title: Rashifall API
                url: ${RASHIFALL_API_URL}
                check-url: ${RASHIFALL_API_CHECK_URL}
              - title: Naukri Service Updater
                url: ${NAUKRI_SERVICE_UPDATER_URL}
                check-url: ${NAUKRI_SERVICE_UPDATER_CHECK_URL}

      - size: full
        widgets:
          - type: search
            autofocus: true
            search-engine: google
            new-tab: true
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
              - title: Github
                shortcut: "!gh"
                url: https://github.com/search?q={QUERY}&type=repositories
              - title: Media Server
                shortcut: "!m"
                url: ${JELLYFIN_URL} + "/web/#/search.html?query={QUERY}"

          - type: monitor
            cache: 1m
            title: Home Assistant
            sites:
              - title: Home Assistant
                url: ${HOME_ASSISTANT_URL}
                check-url: ${HOME_ASSISTANT_CHECK_URL}
                icon: di:home-assistant

          - type: monitor
            cache: 1m
            title: Media Server
            sites:
              - title: Jellyfin
                url: ${JELLYFIN_URL}
                check-url: ${JELLYFIN_CHECK_URL}
                icon: di:jellyfin
              - title: Plex
                url: ${PLEX_URL}
                check-url: ${PLEX_CHECK_URL}
                icon: di:plex
                alt-status-codes: [401, 403]
              - title: Jellyseerr
                url: ${JELLYSEERR_URL}
                check-url: ${JELLYSEERR_CHECK_URL}
                icon: di:jellyseerr
              - title: qBittorrent
                url: ${QBITTORRENT_URL}
                check-url: ${QBITTORRENT_CHECK_URL}
                icon: di:qbittorrent
              - title: Sonarr
                url: ${SONARR_URL}
                check-url: ${SONARR_CHECK_URL}
                icon: di:sonarr
              - title: Radarr
                url: ${RADARR_URL}
                check-url: ${RADARR_CHECK_URL}
                icon: di:radarr
              - title: Prowlarr
                url: ${PROWLARR_URL}
                check-url: ${PROWLARR_CHECK_URL}
                icon: di:prowlarr

          - type: monitor
            cache: 1m
            title: Surveillance
            sites:
              - title: Frigate
                url: ${FRIGATE_URL}
                check-url: ${FRIGATE_CHECK_URL}
                icon: di:frigate
                alt-status-codes: [401, 403]

          - type: monitor
            cache: 1m
            title: Cloud Server
            sites:
              - title: Nextcloud
                url: ${NEXTCLOUD_URL}
                check-url: ${NEXTCLOUD_CHECK_URL}
                icon: di:nextcloud
              - title: File Browser
                url: ${FILEBROWSER_URL}
                check-url: ${FILEBROWSER_CHECK_URL}
                icon: di:filebrowser

          - type: monitor
            cache: 1m
            title: Infrastructure
            sites:
              - title: Portainer
                url: ${PORTAINER_URL}
                check-url: ${PORTAINER_CHECK_URL}
                icon: di:portainer
              - title: AdGuard Home
                url: ${ADGUARD_URL}
                check-url: ${ADGUARD_CHECK_URL}
                icon: di:adguard-home
              - title: Nginx Proxy Manager
                url: ${NGINX_PROXY_MANAGER_URL}
                check-url: ${NGINX_PROXY_MANAGER_CHECK_URL}
                icon: di:nginx-proxy-manager
              - title: Heimdall
                url: ${HEIMDALL_URL}
                check-url: ${HEIMDALL_CHECK_URL}
                icon: di:heimdall

branding:
  custom-footer: |
    <p>Powered by <a href="https://github.com/ctadel/homelab">ctadel</a></p>
