version: "3.9"

networks:
  homeserver:
    driver: bridge

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    restart: unless-stopped
    shm_size: "512mb"
    stop_grace_period: 30s

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # Hardware acceleration (Raspberry Pi 5)

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/frigate/:/config
      - ${MEDIA_DIR}/frigate/:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000  # 1GB

    ports:
      - "8971:8971"       # Frigate UI
      - "8554:8554"       # RTSP feeds
      - "8555:8555/tcp"   # WebRTC (TCP)
      - "8555:8555/udp"   # WebRTC (UDP)

    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - homeserver
