networks:
  watchnet:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 9090:9090
    volumes:
      - ${CONFIG_DIR}/prometheus/:/prometheus
      - ../.config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - watchnet
    restart: unless-stopped
