version: '3.9'

networks:
  stats:
    driver: bridge

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - stats
    ports:
      - 9100:9100
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
