networks:
  watchnet:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONFIG_DIR}/grafana/:/var/lib/grafana
      - ../.config/grafana/dashboards:/etc/grafana/dashboards:ro
      - ../.config/grafana/provisioning:/etc/grafana/provisioning/dashboards/:ro
    ports:
      - 9050:3000
    networks:
      - watchnet
    restart: unless-stopped
