networks:
  stats:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 9090:9090
    volumes:
      - ${CONFIG_DIR}/prometheus/:/prometheus
      - ../configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - stats
    restart: unless-stopped
