networks:
  servicenet:
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../.config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../.config/mosquitto/passwd:/mosquitto/config/passwd
    networks:
      - servicenet
