networks:
  infranet:
    external: true

services:
  glance:
    container_name: glance
    image: glanceapp/glance
    env_file:
      - ../.config/glance/local.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.config/glance/:/app/config
      - /data/media:/mnt/media
      - /data/config:/mnt/config
      - /:/mnt/host
    ports:
      - "8881:8080"
    networks:
      - infranet
    restart: unless-stopped

  glance_private:
    container_name: glance_private
    image: glanceapp/glance
    env_file:
      - ../.config/glance/private.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.config/glance/:/app/config
      - /data/media:/mnt/media
      - /data/config:/mnt/config
      - /:/mnt/host

    ports:
      - "80:8080"
    networks:
      - infranet
    restart: unless-stopped

  glance_public:
    container_name: glance_public
    image: glanceapp/glance
    env_file:
      - ../.config/glance/public.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.config/glance/:/app/config
      - /data/media:/mnt/media
      - /data/config:/mnt/config
      - /:/mnt/host
    ports:
      - "8882:8080"
    networks:
      - infranet
    restart: unless-stopped
