networks:
  infra:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/portainer:/data
    ports:
      - "9000:9000"
    networks:
      - infra
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
