mqtt:
  prefix: lnxlink
  clientId: griham
  server: 192.168.10.100
  port: 1883
  auth:
    user: admin
    pass: admin
    tls: false
    keyfile: ''
    certfile: ''
    ca_certs: ''
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 5
update_on_change: false
modules:
- shutdown
- restart
- suspend
- cpu
- memory
- disk_usage
- temperature
hass_url: null
hass_api: null
custom_modules: null
exclude:
- audio_select
- bash
- battery
- beacondb
- boot_select
- brightness
- fullscreen
- gpio
- gpu
- idle
- inference_time
- ir_remote
- keep_alive
- keyboard_hotkeys
- media
- mouse
- network
- notify
- restful
- screen_onoff
- screenshot
- send_keys
- speech_recognition
- systemd
- webcam
- xdg_open
settings:
  systemd: null
  gpio:
    inputs: null
    outputs: null
  hotkeys: null
  battery:
    include_batteries: []
    exclude_batteries: []
  disk_usage:
    include_disks: []
    exclude_disks: []
  statistics: https://analyzer.bkbilly.workers.dev
  bash:
    allow_any_command: false
    expose: null
  mounts:
    autocheck: false
    directories: []
  ir_remote:
    receiver: null
    transmitter: null
    buttons: []
  restful:
    port: 8112
